# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unmixing_corrected_gof1 <- function(sources, samples, trials = 100L, iter = 100L, seed = 69512L) {
    .Call('_fingerPro_unmixing_corrected_gof1', PACKAGE = 'fingerPro', sources, samples, trials, iter, seed)
}

